//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<int> FilmId { get; set; }
        public Nullable<int> HallId { get; set; }
        public Nullable<System.DateTime> ShowDateTime { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Halls Halls { get; set; }
    }
}
